<?php

function etype_paywall_preprocess_node(&$variables) {
  if (Drupal::currentUser()->isAnonymous()) {
    if (node_is_page($variables['node'])) {
      $nodeType = $variables['node']->getType();
      $config = Drupal::config('etype_paywall.settings');
      $arr = [];
      foreach ($config->get('nodeType') as $type) {
        if ($type !== 0) {
          $arr[] = $type;
        }
      }
      if(in_array($nodeType, $arr)){
        $variables['#attached']['library'][] = 'etype_paywall/etype_paywall';
        $subLink = $config->get('subLink');
        if (empty($subLink)) {
          $e_editions = etype_e_editions();
          $subLink = $e_editions[0]['path'];
        }
        $variables['#attached']['drupalSettings']['etype_paywall']['etype_paywall']['subLink'] = $subLink;
        $variables['#attached']['drupalSettings']['etype_paywall']['etype_paywall']['freeNumber'] = $config->get('freeNumber');
        $variables['#attached']['drupalSettings']['etype_paywall']['etype_paywall']['expiresNumber'] = $config->get('expiresNumber');
      }
    }
  }
}
