# Schema for the configuration files of the trusttxt module.
trusttxt.settings:
  type: config_object
  label: 'trust.txt settings'
  mapping:
    content:
      type: string
      label: 'Contents of trust.txt'
