<?php
/**
 * @file
 * eType Wire Content module file.
 */

/**
 * Callback function for the cron job.
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function _etype_wire_content_node_export() {
  $job = new Drupal\etype_xml_importer\Controller\ImportOliveXMLController;
  $job->ImportOliveXml();
}


/**
 * @return bool
 */
function _etype_wire_content_check_connection() {
  global $databases;
  var_dump($databases);
  if (empty ($databases['default']['wire']['database'] || !isset
    ($databases['default']['wire']['database']))) {
    return FALSE;
  } else {
    return TRUE;
  }
}