<?php
/**
 * @file
 * eType Wire Content module file.
 *
 * TODO: Make View pick up settings for Groups and Site Name.
 */

use Drupal\Core\Database\Database;
use Drupal\etype_wire_content\Controller\WireContentExportController;

/**
 * Callback function for the cron job.
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function _etype_wire_content_node_export() {
  $job = new Drupal\etype_wire_content\Controller\WireContentExportController;
  $job->exportWireContent();
}

/**
 * Check database settings exist.
 *
 * @return bool
 */
function _etype_wire_content_check_connection() {
  return (bool) Database::getConnectionInfo('wire');
}

/**
 * @param \Drupal\node\NodeInterface $node
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function etype_wire_content_node_update(Drupal\node\NodeInterface $node) {
  $exporter = new WireContentExportController();
  $exporter->exportWireContent();
}

/**
 * Filter Wire Content to remove site's own stories and only show stories from papers in selected Groups.
 *
 * @param $view
 * @param $query
 */
function etype_wire_content_views_query_alter($view, $query) {
  if ($view->id() == 'wire_content') {
    $config = Drupal::config('etype_wire_content.settings');
    $groups = $config->get('groups');
    $host = Drupal::request()->getHost();
    $arr = explode(".", $host);;
    if (strpos($arr[1], 'etypegoogle') !== false) {
      $site = $arr[0];
    } else {
      $site = $arr[1];
    }
    // Check for existing filters
    $groupNumber = 0;
    foreach ($query->where as &$condition_group) {
      $groupNumber ++;
    }
    $groupNumber ++;
    $query->addWhere($groupNumber, 'wire_node.site', "%$site%", 'NOT LIKE');
    $groupNumber ++;
    $query->setWhereGroup('OR', $groupNumber);
    foreach ($groups as $group) {
      if (strlen($group) > 1) {
        $query->addWhere($groupNumber, 'wire_node.cluster', "%$group%", 'LIKE');
      }
    }
  }
}
