<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function etype_commerce_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add to cart form id for product 5 is: commerce_order_item_add_to_cart_form_commerce_product_5
  // Then it's enough to check $form_id contains the string 'commerce_order_item_add_to_cart_form_commerce'
  if(strpos($form_id, 'commerce_order_item_add_to_cart_form_commerce') !== false) {
    $form['actions']['submit']['#value'] = t('Checkout');
    $form['actions']['submit']['#submit'][] = '_redirect_to_checkout';
  }
  elseif($form_id == 'commerce_checkout_flow_multistep_default') {
    $form['#attached']['library'][] = 'etype_commerce/login-form';
  }

}

/**
 * Callback for form submission.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *
 * @see hook_form_alter()
 *
 */
function _redirect_to_checkout(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_order\Entity\OrderInterface $cart_id */
  $cart_id = $form_state->get('cart_id');
  $url = Url::fromRoute('commerce_checkout.form',
    ['commerce_order' => $cart_id]
  );
  $form_state->setRedirectUrl($url);
}

/**
 * Implements etype_commerce_preprocess_page_title()
 *
 * @param $variables
 */
function etype_commerce_preprocess_page_title(&$variables) {
  $current_url = Url::fromRoute('<current>');
  $url = $current_url->getInternalPath();
  // Update Checkout page title.
  if(preg_match("/^checkout\/.*\/login/", $url)) {
    if (\Drupal::currentUser()->isAnonymous()) {
      $variables['title'] = 'Log in or create a new account to buy a subscription.';
    }
    else {
      $variables['title'] = 'Renew your subscription';
    }
  }
}

/**
 * Callback function for the cron job.
 *
 * @throws \Exception
 */
function _etype_commerce_expire_subscribers() {
  $job = new Drupal\etype_commerce\Controller\ExpireSubscribersController;
  $job->expireSubscribers();
}

/**
 * Implements hook_page_attachments().
 * css hides system login link.
 *
 * @param array $page
 */
function etype_commerce_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'etype_commerce/global-styling';
}
