#!/usr/bin/php
<?php

// Path to sites.php file.
include(__DIR__ . '/../web/sites/sites.php');
$done = [];
$argv = $_SERVER['argv'];

array_shift($_SERVER['argv']);
$parameters = implode(' ', $_SERVER['argv']);
$commandPattern = "drush9 --uri=:key $parameters";

foreach ($sites as $key => $site) {

    if (count($argv) > 1 && !in_array($site, $done)) {

        $command = str_replace(':key', $key, $commandPattern);
        echo "Executing command `$command` on $site\n";
        `$command`;
        $done[] = $site;
    }

}